#Week6 Day4 Exercises Mandatory

#Exercise 1

my_fav_numbers = {11, 9, 1994}
print(my_fav_numbers)
my_fav_numbers.add(2022)
my_fav_numbers.add(2023)
print(my_fav_numbers)
#last number : what does it mean in a set where items are unordered ?? the last appended one ? the last one when printing ?...
my_fav_numbers.remove(2023)
print(my_fav_numbers)
friend_fav_numbers = {30, 12, 1991}
concat = set.union(my_fav_numbers, friend_fav_numbers)
print(concat)


print("\n")
#Exercise 2
"""In a Tuple, it's not possible to change, add or remove items"""

#Exercise 3

for i in range (1,21):
    print(i, end=' ')


print("\n")
# Exercise 4
"""
1. Recap – What is a float? What is the difference between an integer and a float?
2. Can you think of another way to generate a sequence of floats?
3. Create a list containing the following sequence 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5 (don’t hard-code the sequence).
"""
#Float is a number (>0 or <0) which includes one or more decimals. An integer has no decimals.
#Floats can be generated by division : only divisions with remainders (ie remainders != 0) are kept.
float_list=[]
for i in range(1,5):
    i = i+0.5
    float_list.append(i)
    i = int(i+0.5)
    float_list.append(i)
print (float_list)

# Exercise 5
"""
1. Remove “Banana” from the list.
2. Remove “Blueberries” from the list.
3. Add “Kiwi” to the end of the list.
4. Add “Apples” to the beginning of the list.
5. Count how many apples are in the basket.
6. Empty the basket.
Print(basket)"""

basket = ["Banana", "Apples", "Oranges", "Blueberries"];
basket.remove("Banana")
basket.remove("Blueberries")
basket.append("Kiwi")
basket.insert(0,"Apples")
print(basket)
print(basket.count("Apples"))
basket.clear()
print(basket)

# Exercise 6
name=""
while name != "Emmanuelle":
    name = input("Please enter your first name: ")

# Exercise 7
"""Given a list, use a loop to print out every element which has an even index."""
my_list = ['first', 'second', 'third', 'fourth', 'fifth', 'sixth']
for i in range(0, len(my_list)):
    if i%2==0:
        print(my_list[i])

# Exercise 8
for i in range (1500, 2501):
    if i%5==0 or i%7==0 or i%5==0 and i%7==0:
        print(i, end=' ')

print("\n")
# Exercise 9
"""
1. Ask the user to input their favorite fruit(s) (one or several fruits).
Hint : Use the built in input method. Ask the user to separate the fruits with a single space, eg. "apple mango cherry".
2. Store the favorite fruit(s) in a list (convert the string of words into a list of words).
3. Now that we have a list of fruits, ask the user to input a name of any fruit.
If the user’s input is in the favorite fruits list, print “You chose one of your favorite fruits! Enjoy!”.
If the user’s input is NOT in the list, print, “You chose a new fruit. I hope you enjoy”."""


fav_fruits_string = input("Please input your favorite fruit(s). Please separate the fruits with a single space, eg. apple mango cherry : ")
fav_fruits_list = list(fav_fruits_string.split())
fav_fruits_other = input("Please input the name of a fruit: ")
if fav_fruits_other in fav_fruits_list :
    print("You chose one of your favorite fruits! Enjoy!")
else:
    print("You chose a new fruit. I hope you enjoy.")

print(fav_fruits_list) # for me

print("\n")
# Exercise 10

"""
1. Write a loop that asks a user to enter a series of pizza toppings, when the user inputs ‘quit’ stop asking for toppings.
2. As they enter each topping, print a message saying you’ll add that topping to their pizza.
3. Upon exiting the loop print all the toppings on the pizza pie and what the total price is (10 + 2.5 for each topping)."""

topping=""
toppings_list = []
while topping != "quit":
    topping = input("Please enter a topping for your pizza (if you don't want an additional topping, please input \"quit\"): ")
    if topping != "quit":
        print("We are happy to add the following topping to your extraordinary pizza :", topping)
        toppings_list.append(topping)
price = 10 + len(toppings_list)*2.5
toppings_string = ', '.join(toppings_list)
print(f"It's our pleasure to add the following toppings to your marvellous pizza: {toppings_string}.\nThank you for paying {price}.")

print("\n")
# Exercise 11
"""A movie theater charges different ticket prices depending on a person’s age.
if a person is under the age of 3, the ticket is free.
if they are between 3 and 12, the ticket is $10.
if they are over the age of 12, the ticket is $15.
Ask a family the age of each person who wants a ticket.
Store the total cost of all the family’s tickets and print it out.
A group of teenagers are coming to your movie theater and want to watch a movie that is restricted for people between the ages of 16 and 21.
Write a program that asks every user for their age, and prints a list of the teens who are permitted to watch the movie."""

ages=[]
age=0
cost=0
total_cost=0
while age != "quit":
    age = input("Please enter the age of one person in the family (if you don't want an additional ticket, please input \"quit\"): ")
    if age == "quit":
        cost=0
        break
    else:
        if int(age) < 3:
            cost = 0
        elif int(age)<12:
            cost=10
        else:
            cost=15
    total_cost = total_cost+cost
print(f"The total price for the family is: {total_cost}$.")
print("\n")
welcome = input("Hello guys, I would like to know the age of each of you. How many are you? ")
count = 0
accepted = []
for count in range(0, int(welcome)):
    name = input("Please enter the name: ")
    age = input(f"Dear {name}, thank you to enter your age: ")
    count = count + 1
    if 15<int(age)<22:
        accepted.append(name)
print(accepted)

print("\n")
# Exercise 12

"""Given a list of names, write a program that asks every user for their age, if they are less than 16 years old remove them from the list.
At the end, print the final list"""

list = ['Paul', 'Pierre', 'Jacques', 'Eyal', 'Or', 'Solveig']
new_list = []
for i in range(0, 6):
    age = input(f"Dear {list[i]}, please enter your age: ")
    if int(age) > 16:
        new_list.append(list[i])
print(new_list)


print("\n")
#Exercice 13
"""
1. Make a list called sandwich_orders and fill it with the names of various sandwiches .
2. Then make an empty list called finished_sandwiches.
3. As each sandwich is made, move it to the list of finished sandwiches.
4. After all the sandwiches have been made, print a message listing each sandwich that was made , such as I made your tuna sandwich."""
""
sandwich_orders = ['burger', 'tuna sandwich', 'sandwich3', 'sandwich4', 'sandwich5']
finished_sandwiches = []
for i in range(0, len(sandwich_orders)):
    #The guy who prepares to the one who speaks to the client
    finished = input(f"Please confirm that {sandwich_orders[i]} is done (any other answer than \'yes\' will be understood as \'no\'): ")
    if finished == 'yes':
        finished_sandwiches.append(sandwich_orders[i])
#The guy who speaks to the client, once all sandwiches are ready, when putting them in the bag
for i in range(0, len(finished_sandwiches)):
    print(f"Our deli made your {finished_sandwiches[i]}")

#Exercise 14

sandwich_orders = ['burger', 'tuna sandwich', 'sandwich3', 'sandwich4', 'sandwich5']
for i in range (0,3):
    sandwich_orders.append('pastrami')
# just to check pastramis are added (before being removed !)
if 'pastrami' in sandwich_orders:
    print('Our deli has run out of pastrami unfortunately')
while 'pastrami' in sandwich_orders:
    sandwich_orders.remove('pastrami')
finished_sandwiches = []
for i in range(0, len(sandwich_orders)):
    #The guy who prepares to the one who speaks to the client
    finished = input(f"Please confirm that {sandwich_orders[i]} is done (any other answer than \'yes\' will be understood as \'no\'): ")
    if finished == 'yes':
        finished_sandwiches.append(sandwich_orders[i])
#The guy who speaks to the client, once all sandwiches are ready, when putting them in the bag
for i in range(0, len(finished_sandwiches)):
    print(f"Our deli made your {finished_sandwiches[i]}")